import type { Product } from '@/types';

const sizes = (available: string[], all: string[] = ['XS', 'S', 'M', 'L', 'XL', 'XXL']) =>
  all.map((size) => ({ size, inStock: available.includes(size) }));

export const products: Product[] = [
  {
    id: 'p01',
    name: 'Riot Tape Heavyweight Tee',
    slug: 'riot-tape-heavyweight-tee',
    price: 48,
    category: 'tees',
    fit: 'unisex',
    colorway: 'Blackout',
    swatch: '#141414',
    description:
      '280gsm boxy tee with a cracked hazard-tape print across the chest. Built thick enough to survive leg day and look better after every wash.',
    tags: ['heavyweight', 'boxy fit', 'graphic'],
    isNew: true,
    variants: sizes(['S', 'M', 'L', 'XL', 'XXL']),
  },
  {
    id: 'p02',
    name: 'Static Mesh Training Tee',
    slug: 'static-mesh-training-tee',
    price: 42,
    category: 'tees',
    fit: "men's",
    colorway: 'Bone',
    swatch: '#EDE8DC',
    description: 'Laser-cut mesh panels down the spine for airflow between sets. Drop-tail hem, no chafe seams.',
    tags: ['breathable', 'drop-tail'],
    variants: sizes(['XS', 'S', 'M', 'L', 'XL']),
  },
  {
    id: 'p03',
    name: 'Corrosion Oversized Hoodie',
    slug: 'corrosion-oversized-hoodie',
    price: 92,
    compareAtPrice: 110,
    category: 'hoodies',
    fit: 'unisex',
    colorway: 'Rust Fade',
    swatch: '#8A3E23',
    description: 'Garment-dyed fleece with an acid-wash gradient. Double hood, kangaroo pocket deep enough for chalk and a phone.',
    tags: ['garment-dyed', 'heavyweight fleece'],
    isLimited: true,
    variants: sizes(['S', 'M', 'L', 'XL', 'XXL']),
  },
  {
    id: 'p04',
    name: 'Voltage Cropped Hoodie',
    slug: 'voltage-cropped-hoodie',
    price: 84,
    category: 'hoodies',
    fit: "women's",
    colorway: 'Toxic Lime',
    swatch: '#C9FF3D',
    description: 'Cropped fit fleece with raw-cut hem and reflective RIOT hit across the back. Runs true to size.',
    tags: ['cropped', 'reflective print'],
    isNew: true,
    variants: sizes(['XS', 'S', 'M', 'L']),
  },
  {
    id: 'p05',
    name: 'Deadlift Reinforced Shorts',
    slug: 'deadlift-reinforced-shorts',
    price: 56,
    category: 'shorts',
    fit: "men's",
    colorway: 'Blackout',
    swatch: '#141414',
    description: '4-way stretch ripstop with a gusseted crotch built for full range of motion under a bar, not just around the block.',
    tags: ['ripstop', '4-way stretch'],
    variants: sizes(['S', 'M', 'L', 'XL', 'XXL']),
  },
  {
    id: 'p06',
    name: 'Static Mesh Layer Shorts',
    slug: 'static-mesh-layer-shorts',
    price: 52,
    category: 'shorts',
    fit: "women's",
    colorway: 'Bone',
    swatch: '#EDE8DC',
    description: 'Two-in-one compression layer with a mesh overlay short. Zero ride-up, side pocket fits a key and card.',
    tags: ['compression liner', 'anti ride-up'],
    variants: sizes(['XS', 'S', 'M', 'L']),
  },
  {
    id: 'p07',
    name: 'Fracture Seamless Leggings',
    slug: 'fracture-seamless-leggings',
    price: 68,
    category: 'leggings',
    fit: "women's",
    colorway: 'Rust Fade',
    swatch: '#8A3E23',
    description: 'Seamless knit with a fractured colour-block print engineered to move with you, not against you, past rep twenty.',
    tags: ['seamless knit', 'squat-proof'],
    isNew: true,
    variants: sizes(['XS', 'S', 'M', 'L', 'XL']),
  },
  {
    id: 'p08',
    name: 'Riot Tape Leggings',
    slug: 'riot-tape-leggings',
    price: 64,
    category: 'leggings',
    fit: "women's",
    colorway: 'Toxic Lime',
    swatch: '#C9FF3D',
    description: 'High-rise compression with a hazard-tape side stripe. Hidden waistband pocket sized for a card and key.',
    tags: ['high-rise', 'side pocket'],
    variants: sizes(['XS', 'S', 'M', 'L', 'XL']),
  },
  {
    id: 'p09',
    name: 'Undercut Stringer Tank',
    slug: 'undercut-stringer-tank',
    price: 36,
    category: 'tees',
    fit: "men's",
    colorway: 'Blackout',
    swatch: '#141414',
    description: 'Deep-cut stringer for arm day. Raw edge armholes, dropped back panel, built to show the work.',
    tags: ['stringer', 'raw edge'],
    variants: sizes(['S', 'M', 'L', 'XL']),
  },
  {
    id: 'p10',
    name: 'Salvage Quarter-Zip',
    slug: 'salvage-quarter-zip',
    price: 78,
    category: 'hoodies',
    fit: 'unisex',
    colorway: 'Bone',
    swatch: '#EDE8DC',
    description: 'Brushed-back quarter-zip for the walk between the car park and the rack. Thumbholes, stand collar.',
    tags: ['brushed fleece', 'thumbholes'],
    variants: sizes(['S', 'M', 'L', 'XL', 'XXL']),
  },
  {
    id: 'p11',
    name: 'Chalk Line Lifting Belt',
    slug: 'chalk-line-lifting-belt',
    price: 74,
    category: 'accessories',
    fit: 'unisex',
    colorway: 'Blackout',
    swatch: '#141414',
    description: '10mm single-prong leather belt with a hazard-stripe underlay. Breaks in, never breaks down.',
    tags: ['10mm leather', 'single-prong'],
    variants: sizes(['S', 'M', 'L', 'XL'], ['S', 'M', 'L', 'XL']),
  },
  {
    id: 'p12',
    name: 'Static Terry Gym Towel',
    slug: 'static-terry-gym-towel',
    price: 22,
    category: 'accessories',
    fit: 'unisex',
    colorway: 'Toxic Lime',
    swatch: '#C9FF3D',
    description: 'Oversized terry towel with a woven RIOT tag. The one thing you actually need in your gym bag.',
    tags: ['oversized', 'woven tag'],
    variants: sizes(['One Size'], ['One Size']),
  },
];

export const categories: { label: string; value: Product['category'] | 'all' }[] = [
  { label: 'All', value: 'all' },
  { label: 'Tees', value: 'tees' },
  { label: 'Hoodies', value: 'hoodies' },
  { label: 'Shorts', value: 'shorts' },
  { label: 'Leggings', value: 'leggings' },
  { label: 'Accessories', value: 'accessories' },
];

export const fits: { label: string; value: Product['fit'] | 'all' }[] = [
  { label: 'All', value: 'all' },
  { label: "Men's", value: "men's" },
  { label: "Women's", value: "women's" },
  { label: 'Unisex', value: 'unisex' },
];
